# Site settings
title: 0xF00F 0xC7C8
email: william+blog@oslers.us
description: > # this means to ignore newlines until "baseurl:"
    Hi, I'm William Osler. This blog documents my experiences and learning in
    various areas of computer science and programming.
baseurl: "/william"         # the subpath of your site, e.g. /blog/
url:     "https://oslers.us" # the base hostname & protocol for your site

# Social media links
github_username: oslerw
linkedin_url: william-osler-8a9919116

# Build settings
markdown: kramdown

# Tag page settings
tag_page_layout: tag_page
tag_page_dir: tag

# Exclude vendor/ for deploy
exclude:
    - vendor
